image: node:boron

stages:
  - build
  - run

install_dependencies:
  stage: prepare_dependencies
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  
  script:
    - npm install
    - export MYSQL_HOST="localhost"
    - export MYSQL_PORT="3306"
    - export MYSQL_USER="root"
    - export MYSQL_PASSWORD="nhuthienthu1"
    - export MYSQL_DATABASE="vizbot"
    - npm run migrate:latest
    - npm run build

run:
  stage: run
  script:
    - npm run start --production
