image: node:latest

stages:
  - prepare_dependencies
  - migrate
  - build

install_dependencies:
  stage: prepare_dependencies
  script:
    - npm -v
    - npm -g install npm@latest
    - npm install

migrate:
  stage: migrate
  script:
    - npm run migrate:latest

build:
  stage: build
  script:
    - npm run build
